export const MYTHS = [
  {
    label: "FOLK THEORY",
    title: "The 7-Lookalikes Theory",
    desc: "Everyone has a few lookalikes somewhere. Maybe true. Maybe not. Still makes you want to check, right?",
    icon: "/globe-icon.png",
    width: 24,
    height: 32,
    alt: "glob icon",
  },
  {
    label: "DOPPELGANGER LORE",
    title: "The Doppelgänger Thought",
    desc: "Your doppelgänger is living a different life. Same face energy. Different city. Different story.",
    icon: "/similarity-analysis-icon.png",
    width: 24,
    height: 32,
    alt: "The Doppelgänger Thought",
  },
  {
    label: "PSYCHOLOGY",
    title: "The Familiar Stranger Effect",
    desc: "Some strangers feel weirdly familiar. That “wait, I know this face” feeling is exactly the point.",
    icon: "/eye-icon.png",
    width: 24,
    height: 32,
    alt: "familiar stranger effect",
  },
  {
    label: "CLOSER THAN YOU THINK",
    title: "The Closer-Than-You-Think Idea",
    desc: "Your face twin could be closer than you think. Same campus. Same city. Same internet. You just haven’t matched yet.",
    icon: "/closer.png",
    width: 24,
    height: 32,
    alt: "The Closer-Than-You-Think Idea",
  },
  {
    label: "THE REAL TWIST",
    title: "The Not-Famous Twist",
    desc: "The wildest matches are usually not celebrities. They’re normal people who somehow look suspiciously like you.",
    icon: "/fire-icon.png",
    width: 26,
    height: 35,
    alt: "the not famous twist",
  },
];
